# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: mkdir build; cd build; cmake .. ; cmake --build .
    displayName: 'Build'

  - script: cd build; ctest
    displayName: 'Run testing'

- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: mkdir build; cd build; cmake .. ; cmake --build .
    displayName: 'Build'

  - script: cd build; ctest
    displayName: 'Run testing'